const firearmdata = [
  {
    'YEAR': 2021,
    'STATE': 'AL',
    'RATE': 26.4,
    'DEATHS': 1315,
    'URL': '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'AK',
    'RATE': 25.2,
    'DEATHS': 182,
    'URL': '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'AZ',
    'RATE': 18.3,
    'DEATHS': 1365,
    'URL': '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'AR',
    'RATE': 23.3,
    'DEATHS': 698,
    'URL': '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'CA',
    'RATE': 9,
    'DEATHS': 3576,
    'URL': '/nchs/pressroom/states/california/ca.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'CO',
    'RATE': 17.8,
    'DEATHS': 1064,
    'URL': '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'CT',
    'RATE': 6.7,
    'DEATHS': 248,
    'URL': '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'DE',
    'RATE': 16.6,
    'DEATHS': 158,
    'URL': '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'FL',
    'RATE': 14.1,
    'DEATHS': 3142,
    'URL': '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'GA',
    'RATE': 20.3,
    'DEATHS': 2200,
    'URL': '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'HI',
    'RATE': 4.8,
    'DEATHS': 71,
    'URL': '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'ID',
    'RATE': 16.3,
    'DEATHS': 309,
    'URL': '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'IL',
    'RATE': 16.1,
    'DEATHS': 1995,
    'URL': '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'IN',
    'RATE': 18.4,
    'DEATHS': 1251,
    'URL': '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'IA',
    'RATE': 11.2,
    'DEATHS': 364,
    'URL': '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'KS',
    'RATE': 17.3,
    'DEATHS': 503,
    'URL': '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'KY',
    'RATE': 21.1,
    'DEATHS': 947,
    'URL': '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'LA',
    'RATE': 29.1,
    'DEATHS': 1314,
    'URL': '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'ME',
    'RATE': 12.6,
    'DEATHS': 178,
    'URL': '/nchs/pressroom/states/maine/me.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'MD',
    'RATE': 15.2,
    'DEATHS': 915,
    'URL': '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'MA',
    'RATE': 3.4,
    'DEATHS': 247,
    'URL': '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'MI',
    'RATE': 15.4,
    'DEATHS': 1544,
    'URL': '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'MN',
    'RATE': 10,
    'DEATHS': 573,
    'URL': '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'MS',
    'RATE': 33.9,
    'DEATHS': 962,
    'URL': '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'MO',
    'RATE': 23.2,
    'DEATHS': 1414,
    'URL': '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'MT',
    'RATE': 25.1,
    'DEATHS': 280,
    'URL': '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'NE',
    'RATE': 10.3,
    'DEATHS': 200,
    'URL': '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'NV',
    'RATE': 19.8,
    'DEATHS': 633,
    'URL': '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'NH',
    'RATE': 8.3,
    'DEATHS': 123,
    'URL': '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'NJ',
    'RATE': 5.2,
    'DEATHS': 475,
    'URL': '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'NM',
    'RATE': 27.8,
    'DEATHS': 578,
    'URL': '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'NY',
    'RATE': 5.4,
    'DEATHS': 1078,
    'URL': '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'NC',
    'RATE': 17.3,
    'DEATHS': 1839,
    'URL': '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'ND',
    'RATE': 16.8,
    'DEATHS': 128,
    'URL': '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'OH',
    'RATE': 16.5,
    'DEATHS': 1911,
    'URL': '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'OK',
    'RATE': 21.2,
    'DEATHS': 836,
    'URL': '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'OR',
    'RATE': 14.9,
    'DEATHS': 670,
    'URL': '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'PA',
    'RATE': 14.8,
    'DEATHS': 1905,
    'URL': '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'RI',
    'RATE': 5.6,
    'DEATHS': 64,
    'URL': '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'SC',
    'RATE': 22.4,
    'DEATHS': 1136,
    'URL': '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'SD',
    'RATE': 14.3,
    'DEATHS': 128,
    'URL': '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'TN',
    'RATE': 22.8,
    'DEATHS': 1569,
    'URL': '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'TX',
    'RATE': 15.6,
    'DEATHS': 4613,
    'URL': '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'UT',
    'RATE': 13.9,
    'DEATHS': 450,
    'URL': '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'VT',
    'RATE': 11.9,
    'DEATHS': 83,
    'URL': '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'VA',
    'RATE': 14.3,
    'DEATHS': 1248,
    'URL': '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'WA',
    'RATE': 11.2,
    'DEATHS': 896,
    'URL': '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'WV',
    'RATE': 17.3,
    'DEATHS': 319,
    'URL': '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'WI',
    'RATE': 13.5,
    'DEATHS': 793,
    'URL': '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    'YEAR': 2021,
    'STATE': 'WY',
    'RATE': 26.1,
    'DEATHS': 155,
    'URL': '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'AL',
    'RATE': 23.6,
    'DEATHS': 1141,
    'URL': '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'AK',
    'RATE': 23.5,
    'DEATHS': 175,
    'URL': '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'AZ',
    'RATE': 16.7,
    'DEATHS': 1265,
    'URL': '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'AR',
    'RATE': 22.6,
    'DEATHS': 673,
    'URL': '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'CA',
    'RATE': 8.5,
    'DEATHS': 3449,
    'URL': '/nchs/pressroom/states/california/ca.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'CO',
    'RATE': 15.4,
    'DEATHS': 922,
    'URL': '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'CT',
    'RATE': 6,
    'DEATHS': 219,
    'URL': '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'DE',
    'RATE': 14.4,
    'DEATHS': 135,
    'URL': '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'FL',
    'RATE': 13.7,
    'DEATHS': 3041,
    'URL': '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'GA',
    'RATE': 17.7,
    'DEATHS': 1897,
    'URL': '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'HI',
    'RATE': 3.4,
    'DEATHS': 50,
    'URL': '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'ID',
    'RATE': 17.6,
    'DEATHS': 321,
    'URL': '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'IL',
    'RATE': 14.1,
    'DEATHS': 1745,
    'URL': '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'IN',
    'RATE': 17.3,
    'DEATHS': 1159,
    'URL': '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'IA',
    'RATE': 11.2,
    'DEATHS': 351,
    'URL': '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'KS',
    'RATE': 16.9,
    'DEATHS': 494,
    'URL': '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'KY',
    'RATE': 20.1,
    'DEATHS': 902,
    'URL': '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'LA',
    'RATE': 26.3,
    'DEATHS': 1183,
    'URL': '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'ME',
    'RATE': 10.4,
    'DEATHS': 153,
    'URL': '/nchs/pressroom/states/maine/me.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'MD',
    'RATE': 13.5,
    'DEATHS': 803,
    'URL': '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'MA',
    'RATE': 3.7,
    'DEATHS': 268,
    'URL': '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'MI',
    'RATE': 14.6,
    'DEATHS': 1454,
    'URL': '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'MN',
    'RATE': 8.9,
    'DEATHS': 513,
    'URL': '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'MS',
    'RATE': 28.6,
    'DEATHS': 818,
    'URL': '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'MO',
    'RATE': 23.9,
    'DEATHS': 1426,
    'URL': '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'MT',
    'RATE': 20.9,
    'DEATHS': 238,
    'URL': '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'NE',
    'RATE': 10.1,
    'DEATHS': 197,
    'URL': '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'NV',
    'RATE': 17,
    'DEATHS': 547,
    'URL': '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'NH',
    'RATE': 8.9,
    'DEATHS': 128,
    'URL': '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'NJ',
    'RATE': 5,
    'DEATHS': 443,
    'URL': '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'NM',
    'RATE': 22.7,
    'DEATHS': 479,
    'URL': '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'NY',
    'RATE': 5.3,
    'DEATHS': 1052,
    'URL': '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'NC',
    'RATE': 16,
    'DEATHS': 1699,
    'URL': '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'ND',
    'RATE': 13.8,
    'DEATHS': 100,
    'URL': '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'OH',
    'RATE': 15.2,
    'DEATHS': 1764,
    'URL': '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'OK',
    'RATE': 20.7,
    'DEATHS': 826,
    'URL': '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'OR',
    'RATE': 13,
    'DEATHS': 592,
    'URL': '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'PA',
    'RATE': 13.6,
    'DEATHS': 1752,
    'URL': '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'RI',
    'RATE': 5.1,
    'DEATHS': 54,
    'URL': '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'SC',
    'RATE': 22,
    'DEATHS': 1131,
    'URL': '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'SD',
    'RATE': 13.6,
    'DEATHS': 120,
    'URL': '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'TN',
    'RATE': 21.3,
    'DEATHS': 1473,
    'URL': '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'TX',
    'RATE': 14.2,
    'DEATHS': 4164,
    'URL': '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'UT',
    'RATE': 13.6,
    'DEATHS': 429,
    'URL': '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'VT',
    'RATE': 11.6,
    'DEATHS': 76,
    'URL': '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'VA',
    'RATE': 13.4,
    'DEATHS': 1174,
    'URL': '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'WA',
    'RATE': 10.9,
    'DEATHS': 864,
    'URL': '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'WV',
    'RATE': 18.1,
    'DEATHS': 325,
    'URL': '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'WI',
    'RATE': 12.2,
    'DEATHS': 717,
    'URL': '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    'YEAR': 2020,
    'STATE': 'WY',
    'RATE': 25.9,
    'DEATHS': 154,
    'URL': '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'AL',
    'RATE': 22.2,
    'DEATHS': 1076,
    'URL': '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'AK',
    'RATE': 24.4,
    'DEATHS': 179,
    'URL': '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'AZ',
    'RATE': 15.1,
    'DEATHS': 1136,
    'URL': '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'AR',
    'RATE': 19.3,
    'DEATHS': 580,
    'URL': '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'CA',
    'RATE': 7.2,
    'DEATHS': 2945,
    'URL': '/nchs/pressroom/states/california/ca.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'CO',
    'RATE': 14.2,
    'DEATHS': 846,
    'URL': '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'CT',
    'RATE': 5.3,
    'DEATHS': 190,
    'URL': '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'DE',
    'RATE': 9.9,
    'DEATHS': 93,
    'URL': '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'FL',
    'RATE': 12.7,
    'DEATHS': 2872,
    'URL': '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'GA',
    'RATE': 15.8,
    'DEATHS': 1695,
    'URL': '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'HI',
    'RATE': 4.4,
    'DEATHS': 62,
    'URL': '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'ID',
    'RATE': 14.2,
    'DEATHS': 255,
    'URL': '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'IL',
    'RATE': 10.8,
    'DEATHS': 1367,
    'URL': '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'IN',
    'RATE': 14.1,
    'DEATHS': 958,
    'URL': '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'IA',
    'RATE': 9.1,
    'DEATHS': 294,
    'URL': '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'KS',
    'RATE': 13.7,
    'DEATHS': 403,
    'URL': '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'KY',
    'RATE': 14.9,
    'DEATHS': 682,
    'URL': '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'LA',
    'RATE': 22.1,
    'DEATHS': 1013,
    'URL': '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'ME',
    'RATE': 11.5,
    'DEATHS': 163,
    'URL': '/nchs/pressroom/states/maine/me.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'MD',
    'RATE': 12.6,
    'DEATHS': 757,
    'URL': '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'MA',
    'RATE': 3.4,
    'DEATHS': 247,
    'URL': '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'MI',
    'RATE': 12.1,
    'DEATHS': 1220,
    'URL': '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'MN',
    'RATE': 8.1,
    'DEATHS': 465,
    'URL': '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'MS',
    'RATE': 24.2,
    'DEATHS': 710,
    'URL': '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'MO',
    'RATE': 20.6,
    'DEATHS': 1252,
    'URL': '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'MT',
    'RATE': 19,
    'DEATHS': 209,
    'URL': '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'NE',
    'RATE': 10.4,
    'DEATHS': 205,
    'URL': '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'NV',
    'RATE': 15.3,
    'DEATHS': 490,
    'URL': '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'NH',
    'RATE': 10.7,
    'DEATHS': 156,
    'URL': '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'NJ',
    'RATE': 4.1,
    'DEATHS': 368,
    'URL': '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'NM',
    'RATE': 22.3,
    'DEATHS': 471,
    'URL': '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'NY',
    'RATE': 3.9,
    'DEATHS': 804,
    'URL': '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'NC',
    'RATE': 13.1,
    'DEATHS': 1397,
    'URL': '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'ND',
    'RATE': 12.4,
    'DEATHS': 93,
    'URL': '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'OH',
    'RATE': 13.3,
    'DEATHS': 1578,
    'URL': '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'OK',
    'RATE': 18.6,
    'DEATHS': 737,
    'URL': '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'OR',
    'RATE': 12.6,
    'DEATHS': 566,
    'URL': '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'PA',
    'RATE': 11.7,
    'DEATHS': 1541,
    'URL': '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'RI',
    'RATE': 4.6,
    'DEATHS': 48,
    'URL': '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'SC',
    'RATE': 19.9,
    'DEATHS': 1012,
    'URL': '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'SD',
    'RATE': 13.1,
    'DEATHS': 113,
    'URL': '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'TN',
    'RATE': 18.4,
    'DEATHS': 1270,
    'URL': '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'TX',
    'RATE': 12.7,
    'DEATHS': 3683,
    'URL': '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'UT',
    'RATE': 12.8,
    'DEATHS': 394,
    'URL': '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'VT',
    'RATE': 9.3,
    'DEATHS': 67,
    'URL': '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'VA',
    'RATE': 11.7,
    'DEATHS': 1025,
    'URL': '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'WA',
    'RATE': 10.7,
    'DEATHS': 842,
    'URL': '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'WV',
    'RATE': 16.6,
    'DEATHS': 300,
    'URL': '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'WI',
    'RATE': 10,
    'DEATHS': 604,
    'URL': '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    'YEAR': 2019,
    'STATE': 'WY',
    'RATE': 22.3,
    'DEATHS': 133,
    'URL': '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'AL',
    'RATE': 21.8,
    'DEATHS': 1064,
    'URL': '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'AK',
    'RATE': 21,
    'DEATHS': 155,
    'URL': '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'AZ',
    'RATE': 15.3,
    'DEATHS': 1147,
    'URL': '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'AR',
    'RATE': 18.9,
    'DEATHS': 573,
    'URL': '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'CA',
    'RATE': 7.5,
    'DEATHS': 3040,
    'URL': '/nchs/pressroom/states/california/ca.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'CO',
    'RATE': 15.2,
    'DEATHS': 889,
    'URL': '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'CT',
    'RATE': 4.9,
    'DEATHS': 186,
    'URL': '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'DE',
    'RATE': 11.6,
    'DEATHS': 107,
    'URL': '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'FL',
    'RATE': 12.9,
    'DEATHS': 2902,
    'URL': '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'GA',
    'RATE': 15.7,
    'DEATHS': 1680,
    'URL': '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'HI',
    'RATE': 4,
    'DEATHS': 59,
    'URL': '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'ID',
    'RATE': 16.6,
    'DEATHS': 294,
    'URL': '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'IL',
    'RATE': 10.9,
    'DEATHS': 1382,
    'URL': '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'IN',
    'RATE': 14.7,
    'DEATHS': 977,
    'URL': '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'IA',
    'RATE': 8.7,
    'DEATHS': 282,
    'URL': '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'KS',
    'RATE': 14.8,
    'DEATHS': 424,
    'URL': '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'KY',
    'RATE': 16.9,
    'DEATHS': 762,
    'URL': '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'LA',
    'RATE': 21.4,
    'DEATHS': 991,
    'URL': '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'ME',
    'RATE': 10.3,
    'DEATHS': 159,
    'URL': '/nchs/pressroom/states/maine/me.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'MD',
    'RATE': 11.7,
    'DEATHS': 707,
    'URL': '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'MA',
    'RATE': 3.5,
    'DEATHS': 258,
    'URL': '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'MI',
    'RATE': 12.9,
    'DEATHS': 1310,
    'URL': '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'MN',
    'RATE': 7.8,
    'DEATHS': 437,
    'URL': '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'MS',
    'RATE': 22.9,
    'DEATHS': 681,
    'URL': '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'MO',
    'RATE': 21.5,
    'DEATHS': 1311,
    'URL': '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'MT',
    'RATE': 17.3,
    'DEATHS': 186,
    'URL': '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'NE',
    'RATE': 9,
    'DEATHS': 183,
    'URL': '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'NV',
    'RATE': 17.9,
    'DEATHS': 550,
    'URL': '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'NH',
    'RATE': 10.8,
    'DEATHS': 155,
    'URL': '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'NJ',
    'RATE': 4.8,
    'DEATHS': 420,
    'URL': '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'NM',
    'RATE': 20.7,
    'DEATHS': 438,
    'URL': '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'NY',
    'RATE': 4.1,
    'DEATHS': 821,
    'URL': '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'NC',
    'RATE': 13.3,
    'DEATHS': 1416,
    'URL': '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'ND',
    'RATE': 11.5,
    'DEATHS': 89,
    'URL': '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'OH',
    'RATE': 13.1,
    'DEATHS': 1555,
    'URL': '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'OK',
    'RATE': 16.8,
    'DEATHS': 665,
    'URL': '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'OR',
    'RATE': 11.7,
    'DEATHS': 519,
    'URL': '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'PA',
    'RATE': 12.5,
    'DEATHS': 1654,
    'URL': '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'RI',
    'RATE': 3.3,
    'DEATHS': 37,
    'URL': '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'SC',
    'RATE': 17.6,
    'DEATHS': 895,
    'URL': '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'SD',
    'RATE': 13.6,
    'DEATHS': 117,
    'URL': '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'TN',
    'RATE': 17.8,
    'DEATHS': 1228,
    'URL': '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'TX',
    'RATE': 12.2,
    'DEATHS': 3522,
    'URL': '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'UT',
    'RATE': 13.2,
    'DEATHS': 397,
    'URL': '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'VT',
    'RATE': 12.8,
    'DEATHS': 82,
    'URL': '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'VA',
    'RATE': 11.8,
    'DEATHS': 1035,
    'URL': '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'WA',
    'RATE': 10.4,
    'DEATHS': 809,
    'URL': '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'WV',
    'RATE': 18.2,
    'DEATHS': 343,
    'URL': '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'WI',
    'RATE': 10.1,
    'DEATHS': 598,
    'URL': '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    'YEAR': 2018,
    'STATE': 'WY',
    'RATE': 21.5,
    'DEATHS': 124,
    'URL': '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'AL',
    'RATE': 22.9,
    'DEATHS': 1124,
    'URL': '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'AK',
    'RATE': 24.5,
    'DEATHS': 180,
    'URL': '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'AZ',
    'RATE': 15.8,
    'DEATHS': 1134,
    'URL': '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'AR',
    'RATE': 20.3,
    'DEATHS': 613,
    'URL': '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'CA',
    'RATE': 7.9,
    'DEATHS': 3184,
    'URL': '/nchs/pressroom/states/california/california.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'CO',
    'RATE': 13.4,
    'DEATHS': 779,
    'URL': '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'CT',
    'RATE': 5.1,
    'DEATHS': 188,
    'URL': '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'DE',
    'RATE': 11.7,
    'DEATHS': 111,
    'URL': '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'FL',
    'RATE': 12.4,
    'DEATHS': 2724,
    'URL': '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'GA',
    'RATE': 15.4,
    'DEATHS': 1623,
    'URL': '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'HI',
    'RATE': 2.5,
    'DEATHS': 39,
    'URL': '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'ID',
    'RATE': 16.4,
    'DEATHS': 280,
    'URL': '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'IL',
    'RATE': 12.1,
    'DEATHS': 1543,
    'URL': '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'IN',
    'RATE': 15.3,
    'DEATHS': 1016,
    'URL': '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'IA',
    'RATE': 9,
    'DEATHS': 293,
    'URL': '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'KS',
    'RATE': 16,
    'DEATHS': 466,
    'URL': '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'KY',
    'RATE': 16.2,
    'DEATHS': 730,
    'URL': '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'LA',
    'RATE': 21.7,
    'DEATHS': 1008,
    'URL': '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'ME',
    'RATE': 11.7,
    'DEATHS': 172,
    'URL': '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'MD',
    'RATE': 12.3,
    'DEATHS': 742,
    'URL': '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'MA',
    'RATE': 3.7,
    'DEATHS': 262,
    'URL': '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'MI',
    'RATE': 11.3,
    'DEATHS': 1138,
    'URL': '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'MN',
    'RATE': 8.2,
    'DEATHS': 465,
    'URL': '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'MS',
    'RATE': 21.5,
    'DEATHS': 632,
    'URL': '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'MO',
    'RATE': 21.5,
    'DEATHS': 1307,
    'URL': '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'MT',
    'RATE': 22.5,
    'DEATHS': 244,
    'URL': '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'NE',
    'RATE': 8.3,
    'DEATHS': 160,
    'URL': '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'NV',
    'RATE': 16.7,
    'DEATHS': 508,
    'URL': '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'NH',
    'RATE': 10.4,
    'DEATHS': 146,
    'URL': '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'NJ',
    'RATE': 5.3,
    'DEATHS': 478,
    'URL': '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'NM',
    'RATE': 18.5,
    'DEATHS': 394,
    'URL': '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'NY',
    'RATE': 3.7,
    'DEATHS': 772,
    'URL': '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'NC',
    'RATE': 13.7,
    'DEATHS': 1430,
    'URL': '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'ND',
    'RATE': 13.2,
    'DEATHS': 103,
    'URL': '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'OH',
    'RATE': 13.7,
    'DEATHS': 1589,
    'URL': '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'OK',
    'RATE': 17.2,
    'DEATHS': 681,
    'URL': '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'OR',
    'RATE': 12.1,
    'DEATHS': 528,
    'URL': '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'PA',
    'RATE': 12.5,
    'DEATHS': 1636,
    'URL': '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'RI',
    'RATE': 3.9,
    'DEATHS': 43,
    'URL': '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'SC',
    'RATE': 17.7,
    'DEATHS': 893,
    'URL': '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'SD',
    'RATE': 11.9,
    'DEATHS': 101,
    'URL': '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'TN',
    'RATE': 18.4,
    'DEATHS': 1246,
    'URL': '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'TX',
    'RATE': 12.4,
    'DEATHS': 3513,
    'URL': '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'UT',
    'RATE': 14,
    'DEATHS': 410,
    'URL': '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'VT',
    'RATE': 11.7,
    'DEATHS': 70,
    'URL': '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'VA',
    'RATE': 11.9,
    'DEATHS': 1041,
    'URL': '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'WA',
    'RATE': 11.1,
    'DEATHS': 849,
    'URL': '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'WV',
    'RATE': 18.6,
    'DEATHS': 348,
    'URL': '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'WI',
    'RATE': 10.6,
    'DEATHS': 624,
    'URL': '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    'YEAR': 2017,
    'STATE': 'WY',
    'RATE': 18.8,
    'DEATHS': 113,
    'URL': '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'AL',
    'RATE': 21.5,
    'DEATHS': 1046,
    'URL': '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'AK',
    'RATE': 23.3,
    'DEATHS': 177,
    'URL': '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'AZ',
    'RATE': 15.2,
    'DEATHS': 1094,
    'URL': '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'AR',
    'RATE': 17.8,
    'DEATHS': 541,
    'URL': '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'CA',
    'RATE': 7.9,
    'DEATHS': 3184,
    'URL': '/nchs/pressroom/states/california/california.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'CO',
    'RATE': 14.3,
    'DEATHS': 812,
    'URL': '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'CT',
    'RATE': 4.6,
    'DEATHS': 172,
    'URL': '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'DE',
    'RATE': 11,
    'DEATHS': 111,
    'URL': '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'FL',
    'RATE': 12.6,
    'DEATHS': 2704,
    'URL': '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'GA',
    'RATE': 15,
    'DEATHS': 1571,
    'URL': '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'HI',
    'RATE': 4.5,
    'DEATHS': 66,
    'URL': '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'ID',
    'RATE': 14.6,
    'DEATHS': 242,
    'URL': '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'IL',
    'RATE': 11.7,
    'DEATHS': 1490,
    'URL': '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'IN',
    'RATE': 15,
    'DEATHS': 997,
    'URL': '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'IA',
    'RATE': 9.2,
    'DEATHS': 288,
    'URL': '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'KS',
    'RATE': 13.4,
    'DEATHS': 383,
    'URL': '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'KY',
    'RATE': 17.5,
    'DEATHS': 772,
    'URL': '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'LA',
    'RATE': 21.3,
    'DEATHS': 987,
    'URL': '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'ME',
    'RATE': 8.3,
    'DEATHS': 123,
    'URL': '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'MD',
    'RATE': 11.9,
    'DEATHS': 707,
    'URL': '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'MA',
    'RATE': 3.4,
    'DEATHS': 242,
    'URL': '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'MI',
    'RATE': 12.3,
    'DEATHS': 1230,
    'URL': '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'MN',
    'RATE': 7.6,
    'DEATHS': 432,
    'URL': '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'MS',
    'RATE': 19.9,
    'DEATHS': 587,
    'URL': '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'MO',
    'RATE': 19,
    'DEATHS': 1144,
    'URL': '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'MT',
    'RATE': 18.9,
    'DEATHS': 194,
    'URL': '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'NE',
    'RATE': 9.1,
    'DEATHS': 171,
    'URL': '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'NV',
    'RATE': 16.8,
    'DEATHS': 498,
    'URL': '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'NH',
    'RATE': 9.3,
    'DEATHS': 132,
    'URL': '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'NJ',
    'RATE': 5.5,
    'DEATHS': 485,
    'URL': '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'NM',
    'RATE': 18.1,
    'DEATHS': 383,
    'URL': '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'NY',
    'RATE': 4.4,
    'DEATHS': 900,
    'URL': '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'NC',
    'RATE': 13.7,
    'DEATHS': 1409,
    'URL': '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'ND',
    'RATE': 11.9,
    'DEATHS': 90,
    'URL': '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'OH',
    'RATE': 12.9,
    'DEATHS': 1524,
    'URL': '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'OK',
    'RATE': 19.6,
    'DEATHS': 766,
    'URL': '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'OR',
    'RATE': 11.9,
    'DEATHS': 513,
    'URL': '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'PA',
    'RATE': 12,
    'DEATHS': 1555,
    'URL': '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'RI',
    'RATE': 4.1,
    'DEATHS': 49,
    'URL': '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'SC',
    'RATE': 17.7,
    'DEATHS': 891,
    'URL': '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'SD',
    'RATE': 13.4,
    'DEATHS': 108,
    'URL': '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'TN',
    'RATE': 17.1,
    'DEATHS': 1148,
    'URL': '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'TX',
    'RATE': 12.1,
    'DEATHS': 3353,
    'URL': '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'UT',
    'RATE': 12.9,
    'DEATHS': 370,
    'URL': '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'VT',
    'RATE': 11.1,
    'DEATHS': 78,
    'URL': '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'VA',
    'RATE': 12.1,
    'DEATHS': 1049,
    'URL': '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'WA',
    'RATE': 9,
    'DEATHS': 686,
    'URL': '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'WV',
    'RATE': 17.5,
    'DEATHS': 332,
    'URL': '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'WI',
    'RATE': 11.4,
    'DEATHS': 664,
    'URL': '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    'YEAR': 2016,
    'STATE': 'WY',
    'RATE': 17.4,
    'DEATHS': 101,
    'URL': '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'AL',
    'RATE': 19.6,
    'DEATHS': 958,
    'URL': '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'AK',
    'RATE': 23.4,
    'DEATHS': 177,
    'URL': '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'AZ',
    'RATE': 13.8,
    'DEATHS': 970,
    'URL': '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'AR',
    'RATE': 16.9,
    'DEATHS': 520,
    'URL': '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'CA',
    'RATE': 7.7,
    'DEATHS': 3095,
    'URL': '/nchs/pressroom/states/california/california.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'CO',
    'RATE': 12.6,
    'DEATHS': 701,
    'URL': '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'CT',
    'RATE': 5.3,
    'DEATHS': 189,
    'URL': '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'DE',
    'RATE': 12.1,
    'DEATHS': 112,
    'URL': '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'FL',
    'RATE': 12,
    'DEATHS': 2559,
    'URL': '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'GA',
    'RATE': 14.1,
    'DEATHS': 1448,
    'URL': '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'HI',
    'RATE': 3.6,
    'DEATHS': 55,
    'URL': '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'ID',
    'RATE': 14.7,
    'DEATHS': 247,
    'URL': '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'IL',
    'RATE': 9.5,
    'DEATHS': 1220,
    'URL': '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'IN',
    'RATE': 12.7,
    'DEATHS': 846,
    'URL': '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'IA',
    'RATE': 7.8,
    'DEATHS': 247,
    'URL': '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'KS',
    'RATE': 11.4,
    'DEATHS': 330,
    'URL': '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'KY',
    'RATE': 15.2,
    'DEATHS': 694,
    'URL': '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'LA',
    'RATE': 20.4,
    'DEATHS': 952,
    'URL': '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'ME',
    'RATE': 9.8,
    'DEATHS': 144,
    'URL': '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'MD',
    'RATE': 11.9,
    'DEATHS': 708,
    'URL': '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'MA',
    'RATE': 3,
    'DEATHS': 213,
    'URL': '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'MI',
    'RATE': 11.7,
    'DEATHS': 1164,
    'URL': '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'MN',
    'RATE': 7.4,
    'DEATHS': 410,
    'URL': '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'MS',
    'RATE': 19.6,
    'DEATHS': 589,
    'URL': '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'MO',
    'RATE': 18.1,
    'DEATHS': 1094,
    'URL': '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'MT',
    'RATE': 19.2,
    'DEATHS': 205,
    'URL': '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'NE',
    'RATE': 8.9,
    'DEATHS': 169,
    'URL': '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'NV',
    'RATE': 14.9,
    'DEATHS': 446,
    'URL': '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'NH',
    'RATE': 8.9,
    'DEATHS': 121,
    'URL': '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'NJ',
    'RATE': 5.4,
    'DEATHS': 475,
    'URL': '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'NM',
    'RATE': 18.6,
    'DEATHS': 390,
    'URL': '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'NY',
    'RATE': 4.2,
    'DEATHS': 849,
    'URL': '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'NC',
    'RATE': 12.5,
    'DEATHS': 1289,
    'URL': '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'ND',
    'RATE': 12.8,
    'DEATHS': 92,
    'URL': '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'OH',
    'RATE': 11.9,
    'DEATHS': 1397,
    'URL': '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'OK',
    'RATE': 18,
    'DEATHS': 706,
    'URL': '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'OR',
    'RATE': 11.4,
    'DEATHS': 486,
    'URL': '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'PA',
    'RATE': 11.4,
    'DEATHS': 1485,
    'URL': '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'RI',
    'RATE': 4.7,
    'DEATHS': 51,
    'URL': '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'SC',
    'RATE': 17.3,
    'DEATHS': 850,
    'URL': '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'SD',
    'RATE': 11.1,
    'DEATHS': 96,
    'URL': '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'TN',
    'RATE': 16,
    'DEATHS': 1075,
    'URL': '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'TX',
    'RATE': 11.7,
    'DEATHS': 3203,
    'URL': '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'UT',
    'RATE': 12.8,
    'DEATHS': 367,
    'URL': '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'VT',
    'RATE': 9.6,
    'DEATHS': 70,
    'URL': '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'VA',
    'RATE': 10.9,
    'DEATHS': 946,
    'URL': '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'WA',
    'RATE': 9.8,
    'DEATHS': 718,
    'URL': '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'WV',
    'RATE': 14,
    'DEATHS': 278,
    'URL': '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'WI',
    'RATE': 10.4,
    'DEATHS': 613,
    'URL': '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    'YEAR': 2015,
    'STATE': 'WY',
    'RATE': 19.6,
    'DEATHS': 113,
    'URL': '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'AL',
    'RATE': 16.9,
    'DEATHS': 815,
    'URL': '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'AK',
    'RATE': 19.2,
    'DEATHS': 145,
    'URL': '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'AZ',
    'RATE': 13.5,
    'DEATHS': 927,
    'URL': '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'AR',
    'RATE': 16.6,
    'DEATHS': 496,
    'URL': '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'CA',
    'RATE': 7.4,
    'DEATHS': 2942,
    'URL': '/nchs/pressroom/states/california/california.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'CO',
    'RATE': 12.2,
    'DEATHS': 663,
    'URL': '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'CT',
    'RATE': 5,
    'DEATHS': 187,
    'URL': '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'DE',
    'RATE': 11.1,
    'DEATHS': 102,
    'URL': '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'FL',
    'RATE': 11.5,
    'DEATHS': 2410,
    'URL': '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'GA',
    'RATE': 13.7,
    'DEATHS': 1391,
    'URL': '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'HI',
    'RATE': 2.6,
    'DEATHS': 40,
    'URL': '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'ID',
    'RATE': 13.2,
    'DEATHS': 213,
    'URL': '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'IL',
    'RATE': 9,
    'DEATHS': 1179,
    'URL': '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'IN',
    'RATE': 12.4,
    'DEATHS': 818,
    'URL': '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'IA',
    'RATE': 7.5,
    'DEATHS': 241,
    'URL': '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'KS',
    'RATE': 11.3,
    'DEATHS': 329,
    'URL': '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'KY',
    'RATE': 13.9,
    'DEATHS': 634,
    'URL': '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'LA',
    'RATE': 19,
    'DEATHS': 896,
    'URL': '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'ME',
    'RATE': 9.4,
    'DEATHS': 133,
    'URL': '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'MD',
    'RATE': 9,
    'DEATHS': 546,
    'URL': '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'MA',
    'RATE': 3.2,
    'DEATHS': 226,
    'URL': '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'MI',
    'RATE': 11.1,
    'DEATHS': 1095,
    'URL': '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'MN',
    'RATE': 6.6,
    'DEATHS': 377,
    'URL': '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'MS',
    'RATE': 18.3,
    'DEATHS': 547,
    'URL': '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'MO',
    'RATE': 15.3,
    'DEATHS': 943,
    'URL': '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'MT',
    'RATE': 16.1,
    'DEATHS': 172,
    'URL': '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'NE',
    'RATE': 9.5,
    'DEATHS': 179,
    'URL': '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'NV',
    'RATE': 14.8,
    'DEATHS': 429,
    'URL': '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'NH',
    'RATE': 8.7,
    'DEATHS': 122,
    'URL': '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'NJ',
    'RATE': 5.3,
    'DEATHS': 468,
    'URL': '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'NM',
    'RATE': 16,
    'DEATHS': 340,
    'URL': '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'NY',
    'RATE': 4.2,
    'DEATHS': 875,
    'URL': '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'NC',
    'RATE': 11.8,
    'DEATHS': 1206,
    'URL': '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'ND',
    'RATE': 12.3,
    'DEATHS': 96,
    'URL': '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'OH',
    'RATE': 10.3,
    'DEATHS': 1211,
    'URL': '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'OK',
    'RATE': 15.7,
    'DEATHS': 611,
    'URL': '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'OR',
    'RATE': 11.7,
    'DEATHS': 497,
    'URL': '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'PA',
    'RATE': 10.5,
    'DEATHS': 1390,
    'URL': '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'RI',
    'RATE': 3,
    'DEATHS': 34,
    'URL': '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'SC',
    'RATE': 15.5,
    'DEATHS': 767,
    'URL': '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'SD',
    'RATE': 10.3,
    'DEATHS': 89,
    'URL': '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'TN',
    'RATE': 15.1,
    'DEATHS': 1016,
    'URL': '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'TX',
    'RATE': 10.7,
    'DEATHS': 2848,
    'URL': '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'UT',
    'RATE': 12.3,
    'DEATHS': 337,
    'URL': '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'VT',
    'RATE': 10.3,
    'DEATHS': 69,
    'URL': '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'VA',
    'RATE': 10.3,
    'DEATHS': 889,
    'URL': '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'WA',
    'RATE': 9.7,
    'DEATHS': 702,
    'URL': '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'WV',
    'RATE': 14.6,
    'DEATHS': 286,
    'URL': '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'WI',
    'RATE': 8.2,
    'DEATHS': 487,
    'URL': '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    'YEAR': 2014,
    'STATE': 'WY',
    'RATE': 16.2,
    'DEATHS': 93,
    'URL': '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'AL',
    'RATE': 16,
    'DEATHS': 736,
    'URL': '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'AK',
    'RATE': 17.5,
    'DEATHS': 116,
    'URL': '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'AZ',
    'RATE': 16.1,
    'DEATHS': 934,
    'URL': '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'AR',
    'RATE': 15.7,
    'DEATHS': 439,
    'URL': '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'CA',
    'RATE': 9.5,
    'DEATHS': 3453,
    'URL': '/nchs/pressroom/states/california/california.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'CO',
    'RATE': 11.6,
    'DEATHS': 535,
    'URL': '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'CT',
    'RATE': 5.3,
    'DEATHS': 187,
    'URL': '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'DE',
    'RATE': 8.8,
    'DEATHS': 75,
    'URL': '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'FL',
    'RATE': 10,
    'DEATHS': 1838,
    'URL': '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'GA',
    'RATE': 12.1,
    'DEATHS': 1064,
    'URL': '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'HI',
    'RATE': 2.1,
    'DEATHS': 28,
    'URL': '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'ID',
    'RATE': 14.1,
    'DEATHS': 195,
    'URL': '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'IL',
    'RATE': 8,
    'DEATHS': 1019,
    'URL': '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'IN',
    'RATE': 11.2,
    'DEATHS': 705,
    'URL': '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'IA',
    'RATE': 6.7,
    'DEATHS': 201,
    'URL': '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'KS',
    'RATE': 9.3,
    'DEATHS': 257,
    'URL': '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'KY',
    'RATE': 13,
    'DEATHS': 548,
    'URL': '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'LA',
    'RATE': 18.5,
    'DEATHS': 858,
    'URL': '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'ME',
    'RATE': 7.8,
    'DEATHS': 109,
    'URL': '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'MD',
    'RATE': 11.9,
    'DEATHS': 657,
    'URL': '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'MA',
    'RATE': 3.4,
    'DEATHS': 224,
    'URL': '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'MI',
    'RATE': 10.8,
    'DEATHS': 1074,
    'URL': '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'MN',
    'RATE': 7,
    'DEATHS': 361,
    'URL': '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'MS',
    'RATE': 16,
    'DEATHS': 455,
    'URL': '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'MO',
    'RATE': 12.9,
    'DEATHS': 752,
    'URL': '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'MT',
    'RATE': 16.9,
    'DEATHS': 161,
    'URL': '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'NE',
    'RATE': 7.7,
    'DEATHS': 135,
    'URL': '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'NV',
    'RATE': 16.1,
    'DEATHS': 390,
    'URL': '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'NH',
    'RATE': 6.6,
    'DEATHS': 88,
    'URL': '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'NJ',
    'RATE': 5.2,
    'DEATHS': 434,
    'URL': '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'NM',
    'RATE': 13.9,
    'DEATHS': 267,
    'URL': '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'NY',
    'RATE': 5.3,
    'DEATHS': 1019,
    'URL': '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'NC',
    'RATE': 12.8,
    'DEATHS': 1119,
    'URL': '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'ND',
    'RATE': 8.8,
    'DEATHS': 61,
    'URL': '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'OH',
    'RATE': 9.6,
    'DEATHS': 1116,
    'URL': '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'OK',
    'RATE': 13.2,
    'DEATHS': 468,
    'URL': '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'OR',
    'RATE': 10.7,
    'DEATHS': 402,
    'URL': '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'PA',
    'RATE': 10.8,
    'DEATHS': 1352,
    'URL': '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'RI',
    'RATE': 3.6,
    'DEATHS': 39,
    'URL': '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'SC',
    'RATE': 13.8,
    'DEATHS': 589,
    'URL': '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'SD',
    'RATE': 10.2,
    'DEATHS': 82,
    'URL': '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'TN',
    'RATE': 16,
    'DEATHS': 976,
    'URL': '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'TX',
    'RATE': 11.1,
    'DEATHS': 2490,
    'URL': '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'UT',
    'RATE': 10.1,
    'DEATHS': 227,
    'URL': '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'VT',
    'RATE': 6.8,
    'DEATHS': 44,
    'URL': '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'VA',
    'RATE': 11.5,
    'DEATHS': 888,
    'URL': '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'WA',
    'RATE': 8.8,
    'DEATHS': 567,
    'URL': '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'WV',
    'RATE': 13.8,
    'DEATHS': 261,
    'URL': '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'WI',
    'RATE': 8.5,
    'DEATHS': 474,
    'URL': '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    'YEAR': 2005,
    'STATE': 'WY',
    'RATE': 13.4,
    'DEATHS': 71,
    'URL': '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
]

export default firearmdata
